"""changes in db 

Revision ID: a84b32f564f7
Revises: 
Create Date: 2025-03-11 12:06:37.681092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84b32f564f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_name', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['project_name'])

    with op.batch_alter_table('story_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_consumed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_details', schema=None) as batch_op:
        batch_op.drop_column('story_consumed')

    with op.batch_alter_table('project_name', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
