"""changes in storydetails tabel add the target_date and actual horse, and estimates horse

Revision ID: f1d095239833
Revises: a84b32f564f7
Create Date: 2025-03-18 16:12:10.041469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d095239833'
down_revision = 'a84b32f564f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_hour', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_details', schema=None) as batch_op:
        batch_op.drop_column('estimated_hour')
        batch_op.drop_column('actual_hour')
        batch_op.drop_column('target_date')

    # ### end Alembic commands ###
